#本地ip
ip: 192.168.10.246

#数据源信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=true&verifyServerCertificate=false&useUnicode=true&characterEncoding=UTF8
    data-username: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
springfox:
  documentation:
    swagger:
      v2:
        path: /